### PR TITLE
hook jsonist.post as well

### PR DESCRIPTION
**Pull request by ralphtheninja**
Needed for `ghissues` to work well on next version.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@rvagg If you could release a new version with this change then I can make a PR to `ghissues` so it also can reuse the tests.

**Comment by rvagg** [comment]
going to add you to npm for all of these repos as well @ralphtheninja, I use all of these fairy heavily but I trust you to do the right thing!

**Comment by ralphtheninja** [comment]
@rvagg Cool!

**Comment by ralphtheninja** [comment]
```
$ npm publish
+ ghutils@1.3.0
```

**Pull request merged**
