### PR TITLE
Link headers

### PR DESCRIPTION
**Pull request by ralphtheninja**
This removes assuming next page is of format `&page=n`. We simply request a page and follow next links from the response header. If no one can be found we stop requesting and callback the result.

This is a breaking change for tests in modules using the test utils from this module (because tests.js was renamed and also because tests in dependants assume paging works the old way). The code should still work though, so I guess this would also have to be a new major just to avoid breaking tests in dependants.

### CODE REVIEW

**Comment by rvagg** [comment]
if this works, you'll be my hero for life, this was a major TODO item and should save an unnecessary request!

**Comment by ralphtheninja** [comment]
@rvagg it seems to work well. I stole it from https://github.com/ralphtheninja/cloneall/blob/master/lib/get-repos.js#L14-L41 :) (which I will port later to use `ghrepos`)

**Comment by ralphtheninja** [comment]
> if this works, you'll be my hero for life, this was a major TODO item and should save an unnecessary request!

Yep. Before we stopped when we got no response back. Now we know when to stop requesting.

**Comment by ralphtheninja** [comment]
If you give me a :+1: I'll merge and release `3.0.0`

**Comment by rvagg** [comment]
:+1: make it so

**Comment by ralphtheninja** [comment]
```
$ npm publish
+ ghutils@3.0.0
```

**Pull request merged**
